services:
  app:
    image: dilrukshiwijesuriya276/label_a:test
    ports:
      - 127.0.0.1:80:80
    working_dir: /app
    volumes:
      - ./:/app
      - ./static:/static
    environment:
      POSTGRES_HOST: labela
      POSTGRES_USER: labela
      POSTGRES_PASSWORD: labela
      POSTGRES_DB: labela
    depends_on:
      - db

  db:
    image: dilrukshiwijesuriya276/label_a:test_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_ROOT_PASSWORD: labela
      POSTGRES_DATABASE: labela
      POSTGRES_HOST: labela
      POSTGRES_USER: labela
      POSTGRES_PASSWORD: labela
      POSTGRES_DB: labela
