# Generated by Django 4.0.3 on 2024-01-18 19:24

from django.db import migrations
from django.conf import settings

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model
    email = settings.DJANGO_SUPERUSER_EMAIL
    password = settings.DJANGO_SUPERUSER_PASSWORD
    user = get_user_model()
    admin = user.objects.create_superuser(
           username=email, password=password, email=email
        )
    admin.save()


def create_products(apps, schema_editor):
     Item = apps.get_model('product', 'Item')
     Item.objects.create(name='CarBattery', price=100.00, description='Made in Japan')
     Item.objects.create(name='BreakPad', price=500.00, description='Made in Japan')
     Item.objects.create(name='SideMirror', price=300.00, description='Made in Japan')


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_cart_delivery'),
    ]

    operations = [
         migrations.RunPython(generate_superuser, generate_superuser),
         migrations.RunPython(create_products, create_products),
    ]
